language: generic
services:
  docker

before_install:
  - docker build -t afed29/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true afed29/react-test npm test

after_success:
  - docker build -t afed29/multi-client ./client
  - docker build -t afed29/multi-nginx ./nginx
  - docker build -t afed29/multi-server ./server
  - docker build -t afed29/multi-worker ./worker

  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push afed29/multi-client
  - docker push afed29/multi-nginx
  - docker push afed29/multi-server
  - docker push afed29/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-357099032582
  bucket_path: docker-multi
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
